- hosts: server
  vars_files:
    - group_vars/vault.yml
    - group_vars/server.yml
  roles:
    - mrlesmithjr.netdata
    - cloudalchemy.prometheus
    - rossmcdonald.influxdb
    - telegraf
    - cloudalchemy.grafana

- hosts: client
  vars_files:
    - group_vars/vault.yml
    - group_vars/client.yml
  roles:
    - mrlesmithjr.netdata